(function () {
  'use strict';

  const ADMIN_EMAIL = 'ab.m.dent.clinic@gmail.com';
  const state = { lang: localStorage.getItem('admin_lang') || 'en', client: null, user: null, section: 'overview', cache: {} };
  const translations = {
    en: { adminLabel: 'CLINIC ADMINISTRATION', welcomeBack: 'Welcome back', loginIntro: 'Sign in to manage your clinic workspace.', email: 'Email', password: 'Password', signIn: 'Sign in', clinicAdmin: 'Clinic Admin', overview: 'Overview', appointments: 'Appointments', patients: 'Patients', services: 'Services', gallery: 'Gallery', doctorProfile: 'Doctor profile', clinicSettings: 'Clinic settings', messages: 'Messages', logout: 'Log out', privateWorkspace: 'PRIVATE WORKSPACE', configurationRequired: 'Configuration required', configurationHelp: 'The local Supabase configuration could not be loaded. Confirm that the root .env.local file is available to your local web server.', loading: 'Loading secure workspace...', todayAppointments: "Today's appointments", pendingAppointments: 'Pending appointments', confirmedAppointments: 'Confirmed appointments', completedAppointments: 'Completed appointments', cancelledAppointments: 'Cancelled appointments', totalPatients: 'Total patients', newMessages: 'New messages', recentAppointments: 'Recent appointments', noAppointments: 'No appointments yet', ready: 'Your workspace is ready for data.', add: 'Add', edit: 'Edit', delete: 'Delete', save: 'Save changes', cancel: 'Cancel', search: 'Search', status: 'Status', date: 'Date', actions: 'Actions', name: 'Name', phone: 'Phone', service: 'Service', notes: 'Notes', time: 'Time', new: 'New', confirmed: 'Confirmed', completed: 'Completed', cancelled: 'Cancelled', active: 'Active', inactive: 'Inactive', noRecords: 'No records found.', loadingData: 'Loading data...', confirmDelete: 'Delete this record permanently?', saved: 'Changes saved.', deleted: 'Record deleted.', error: 'Something went wrong.', loginFailed: 'Unable to sign in. Check your email and password.', accessDenied: 'This account is not authorized for the clinic dashboard.', signedOut: 'You have been signed out.', biography: 'Biography', qualifications: 'Qualifications', fellowship: 'Fellowship', image: 'Image', category: 'Category', title: 'Title', price: 'Price', address: 'Address', workingHours: 'Working hours', instagram: 'Instagram', googleMaps: 'Google Maps URL', message: 'Message', read: 'Read', unread: 'Unread', markRead: 'Mark read', clinicName: 'Clinic name', upload: 'Upload image', selectSection: 'Select a section from the sidebar.' },
    ar: { adminLabel: 'إدارة العيادة', welcomeBack: 'مرحبًا بعودتك', loginIntro: 'سجّل الدخول لإدارة مساحة عيادتك.', email: 'البريد الإلكتروني', password: 'كلمة المرور', signIn: 'تسجيل الدخول', clinicAdmin: 'إدارة العيادة', overview: 'نظرة عامة', appointments: 'المواعيد', patients: 'المرضى', services: 'الخدمات', gallery: 'المعرض', doctorProfile: 'ملف الدكتور', clinicSettings: 'إعدادات العيادة', messages: 'الرسائل', logout: 'تسجيل الخروج', privateWorkspace: 'مساحة خاصة', configurationRequired: 'الإعداد مطلوب', configurationHelp: 'تعذر تحميل إعدادات Supabase المحلية. تأكد من أن ملف .env.local متاح لخادم الويب المحلي.', loading: 'جارٍ تحميل المساحة الآمنة...', todayAppointments: 'مواعيد اليوم', pendingAppointments: 'المواعيد المعلقة', confirmedAppointments: 'المواعيد المؤكدة', completedAppointments: 'المواعيد المكتملة', cancelledAppointments: 'المواعيد الملغاة', totalPatients: 'إجمالي المرضى', newMessages: 'الرسائل الجديدة', recentAppointments: 'أحدث المواعيد', noAppointments: 'لا توجد مواعيد بعد', ready: 'مساحتك جاهزة للبيانات.', add: 'إضافة', edit: 'تعديل', delete: 'حذف', save: 'حفظ التغييرات', cancel: 'إلغاء', search: 'بحث', status: 'الحالة', date: 'التاريخ', actions: 'الإجراءات', name: 'الاسم', phone: 'الهاتف', service: 'الخدمة', notes: 'ملاحظات', time: 'الوقت', new: 'جديد', confirmed: 'مؤكد', completed: 'مكتمل', cancelled: 'ملغى', active: 'نشط', inactive: 'غير نشط', noRecords: 'لا توجد سجلات.', loadingData: 'جارٍ تحميل البيانات...', confirmDelete: 'هل تريد حذف هذا السجل نهائيًا؟', saved: 'تم حفظ التغييرات.', deleted: 'تم حذف السجل.', error: 'حدث خطأ.', loginFailed: 'تعذر تسجيل الدخول. تحقق من البريد وكلمة المرور.', accessDenied: 'هذا الحساب غير مصرح له بدخول لوحة العيادة.', signedOut: 'تم تسجيل الخروج.', biography: 'السيرة الذاتية', qualifications: 'المؤهلات', fellowship: 'الزمالة', image: 'الصورة', category: 'التصنيف', title: 'العنوان', price: 'السعر', address: 'العنوان', workingHours: 'ساعات العمل', instagram: 'إنستجرام', googleMaps: 'رابط خرائط جوجل', message: 'الرسالة', read: 'مقروءة', unread: 'غير مقروءة', markRead: 'تحديد كمقروءة', clinicName: 'اسم العيادة', upload: 'رفع صورة', selectSection: 'اختر قسمًا من القائمة الجانبية.' }
  };
  const $ = (selector) => document.querySelector(selector);
  const $$ = (selector) => Array.from(document.querySelectorAll(selector));
  const text = (key) => translations[state.lang][key] || key;
  const esc = (value) => String(value ?? '').replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
  const field = (label, name, value = '', type = 'text', required = false) => `<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${required ? 'required' : ''}></label>`;
  const area = (label, name, value = '') => `<label>${esc(label)}<textarea name="${name}" rows="3">${esc(value)}</textarea></label>`;

  function applyLanguage() { document.documentElement.lang = state.lang; document.documentElement.dir = state.lang === 'ar' ? 'rtl' : 'ltr'; $$('[data-i18n]').forEach((element) => { element.textContent = text(element.dataset.i18n); }); $$('[data-language-toggle]').forEach((button) => { button.textContent = state.lang === 'ar' ? 'EN' : 'العربية'; }); }
  function show(view) { ['loading-view', 'login-view', 'dashboard-view', 'configuration-view'].forEach((id) => { const element = $('#' + id); if (element) element.hidden = id !== view; }); }
  function toast(message, error = false) { const element = $('#toast'); element.textContent = message; element.classList.toggle('error', error); element.classList.add('show'); window.setTimeout(() => element.classList.remove('show'), 3500); }
  function busy(isBusy) { $('#dashboard-content').classList.toggle('is-loading', isBusy); }
  function normalizeError(error) { return error?.message || text('error'); }

  function loadEnvironment() { const config = window.ADMIN_SUPABASE_CONFIG; if (!config?.url || !config?.publishableKey?.startsWith('sb_publishable_')) throw new Error('Invalid publishable configuration'); return { VITE_SUPABASE_URL: config.url, VITE_SUPABASE_PUBLISHABLE_KEY: config.publishableKey }; }
  async function query(table, options = {}) { let request = state.client.from(table).select(options.select || '*'); if (options.order) request = request.order(options.order, { ascending: options.ascending ?? false }); if (options.limit) request = request.limit(options.limit); if (options.filters) Object.entries(options.filters).forEach(([key, value]) => { request = request.eq(key, value); }); const result = await request; if (result.error) throw result.error; return result.data || []; }
  async function count(table, filters = {}) { let request = state.client.from(table).select('*', { count: 'exact', head: true }); Object.entries(filters).forEach(([key, value]) => { request = request.eq(key, value); }); const result = await request; if (result.error) throw result.error; return result.count || 0; }
  async function save(table, id, values) { const result = id ? await state.client.from(table).update(values).eq('id', id).select().single() : await state.client.from(table).insert(values).select().single(); if (result.error) throw result.error; return result.data; }
  async function remove(table, id) { const result = await state.client.from(table).delete().eq('id', id); if (result.error) throw result.error; }

  function renderShell(title, body, action = '') { $('#page-title').textContent = title; $('#dashboard-content').innerHTML = `<div class="section-heading"><div><p class="eyebrow">${state.lang === 'ar' ? 'مساحة الإدارة' : 'Management workspace'}</p><h2>${esc(title)}</h2></div>${action}</div>${body}`; }
  function loadingView() { $('#dashboard-content').innerHTML = `<div class="loading-inline">${text('loadingData')}</div>`; }
  function emptyView() { return `<div class="empty-state"><div><strong>${text('noRecords')}</strong><span>${text('selectSection')}</span></div></div>`; }
  function statusBadge(status) { return `<span class="status status-${esc(status)}">${esc(text(status))}</span>`; }
  function tableView(headers, rows) { return `<div class="table-wrap"><table><thead><tr>${headers.map((header) => `<th>${esc(header)}</th>`).join('')}</tr></thead><tbody>${rows || `<tr><td colspan="${headers.length}">${emptyView()}</td></tr>`}</tbody></table></div>`; }
  function modal(title, body, submitLabel = text('save')) { const container = document.createElement('div'); container.className = 'modal-backdrop'; container.innerHTML = `<section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-head"><h2 id="modal-title">${esc(title)}</h2><button type="button" class="modal-close" data-close-modal aria-label="${esc(text('cancel'))}">×</button></div><form id="modal-form" class="modal-form">${body}<div class="modal-actions"><button type="button" class="button button-quiet" data-close-modal>${esc(text('cancel'))}</button><button type="submit" class="button button-primary">${esc(submitLabel)}</button></div></form></section>`; document.body.appendChild(container); container.querySelectorAll('[data-close-modal]').forEach((button) => button.addEventListener('click', () => container.remove())); return container; }

  async function renderOverview() { busy(true); try { const today = new Date().toISOString().slice(0, 10); const [todayCount, pending, confirmed, completed, cancelled, patients, messages, recent] = await Promise.all([count('appointments', { preferred_date: today }), count('appointments', { status: 'new' }), count('appointments', { status: 'confirmed' }), count('appointments', { status: 'completed' }), count('appointments', { status: 'cancelled' }), count('patients'), count('contact_messages', { status: 'unread' }), query('appointments', { order: 'created_at', limit: 5 })]); const rows = recent.map((item) => `<tr><td>${esc(item.patient_name)}</td><td>${esc(item.service || '-')}</td><td>${esc(item.preferred_date || '-')}</td><td>${statusBadge(item.status)}</td></tr>`).join(''); renderShell(text('overview'), `<section class="stats-grid"><article class="stat-card"><p>${text('todayAppointments')}</p><strong>${todayCount}</strong><small>${esc(today)}</small></article><article class="stat-card"><p>${text('pendingAppointments')}</p><strong>${pending}</strong><small>${text('new')}</small></article><article class="stat-card"><p>${text('confirmedAppointments')}</p><strong>${confirmed}</strong><small>${text('confirmed')}</small></article><article class="stat-card"><p>${text('completedAppointments')}</p><strong>${completed}</strong><small>${text('completed')}</small></article><article class="stat-card"><p>${text('cancelledAppointments')}</p><strong>${cancelled}</strong><small>${text('cancelled')}</small></article><article class="stat-card"><p>${text('totalPatients')}</p><strong>${patients}</strong><small>${text('patients')}</small></article><article class="stat-card"><p>${text('newMessages')}</p><strong>${messages}</strong><small>${text('messages')}</small></article></section><section class="panel full-panel"><div class="panel-title"><h3>${text('recentAppointments')}</h3><button class="button button-quiet" data-go="appointments">${text('details')}</button></div>${tableView([text('name'), text('service'), text('date'), text('status')], rows)}</section>`); $$('[data-go]').forEach((button) => button.addEventListener('click', () => navigate(button.dataset.go))); } catch (error) { renderShell(text('overview'), `<div class="error-state">${esc(normalizeError(error))}</div>`); } finally { busy(false); } }

  async function renderAppointments() { loadingView(); try { const data = await query('appointments', { order: 'created_at' }); state.cache.appointments = data; const rows = data.map((item) => `<tr><td>${esc(item.patient_name)}</td><td>${esc(item.phone)}</td><td>${esc(item.service || '-')}</td><td>${esc(item.preferred_date || '-')} ${esc(item.preferred_time || '')}</td><td>${statusBadge(item.status)}</td><td><div class="row-actions"><button class="small-button" data-edit-appointment="${item.id}">${text('edit')}</button><button class="small-button danger" data-delete="appointments" data-id="${item.id}">${text('delete')}</button></div></td></tr>`).join(''); renderShell(text('appointments'), `<div class="toolbar"><input id="module-search" placeholder="${esc(text('search'))}" aria-label="${esc(text('search'))}"><select id="status-filter" aria-label="${esc(text('status'))}"><option value="">${text('status')}</option><option value="new">${text('new')}</option><option value="confirmed">${text('confirmed')}</option><option value="completed">${text('completed')}</option><option value="cancelled">${text('cancelled')}</option></select><button class="button button-primary" id="add-appointment">+ ${text('add')}</button></div><div id="module-table">${tableView([text('name'), text('phone'), text('service'), `${text('date')} / ${text('time')}`, text('status'), text('actions')], rows)}</div>`); wireAppointmentControls(); } catch (error) { renderShell(text('appointments'), `<div class="error-state">${esc(normalizeError(error))}</div>`); } }
  function appointmentForm(item = {}) { return `${field(text('name'), 'patient_name', item.patient_name, 'text', true)}${field(text('phone'), 'phone', item.phone, 'tel', true)}${field(text('email'), 'email', item.email, 'email')}${field(text('service'), 'service', item.service)}${field(text('date'), 'preferred_date', item.preferred_date, 'date')}${field(text('time'), 'preferred_time', item.preferred_time, 'time')}${area(text('notes'), 'notes', item.notes)}<label>${text('status')}<select name="status"><option value="new" ${item.status === 'new' ? 'selected' : ''}>${text('new')}</option><option value="confirmed" ${item.status === 'confirmed' ? 'selected' : ''}>${text('confirmed')}</option><option value="completed" ${item.status === 'completed' ? 'selected' : ''}>${text('completed')}</option><option value="cancelled" ${item.status === 'cancelled' ? 'selected' : ''}>${text('cancelled')}</option></select></label>`; }
  function wireAppointmentControls() { $('#add-appointment').addEventListener('click', () => openAppointment()); $('#module-search').addEventListener('input', filterAppointments); $('#status-filter').addEventListener('change', filterAppointments); $$('[data-edit-appointment]').forEach((button) => button.addEventListener('click', () => openAppointment(state.cache.appointments.find((item) => item.id === button.dataset.editAppointment)))); wireDeleteButtons(); }
  function filterAppointments() { const search = $('#module-search').value.toLowerCase(); const status = $('#status-filter').value; const data = state.cache.appointments.filter((item) => (!status || item.status === status) && (!search || `${item.patient_name} ${item.phone} ${item.service}`.toLowerCase().includes(search))); const rows = data.map((item) => `<tr><td>${esc(item.patient_name)}</td><td>${esc(item.phone)}</td><td>${esc(item.service || '-')}</td><td>${esc(item.preferred_date || '-')} ${esc(item.preferred_time || '')}</td><td>${statusBadge(item.status)}</td><td><div class="row-actions"><button class="small-button" data-edit-appointment="${item.id}">${text('edit')}</button><button class="small-button danger" data-delete="appointments" data-id="${item.id}">${text('delete')}</button></div></td></tr>`).join(''); $('#module-table').innerHTML = tableView([text('name'), text('phone'), text('service'), `${text('date')} / ${text('time')}`, text('status'), text('actions')], rows); wireAppointmentControls(); }
  function openAppointment(item) { const dialog = modal(item ? text('edit') : text('add'), appointmentForm(item)); dialog.querySelector('#modal-form').addEventListener('submit', async (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); try { await save('appointments', item?.id, values); dialog.remove(); toast(text('saved')); renderAppointments(); } catch (error) { toast(normalizeError(error), true); } }); }

  async function renderPatients() { await renderCrudList('patients', [text('name'), text('phone'), text('email'), text('actions')], (item) => `<td>${esc(item.name)}</td><td>${esc(item.phone)}</td><td>${esc(item.email || '-')}</td>`, patientForm, (item) => `<button class="small-button" data-history="${item.id}">${text('details')}</button>`); }
  function patientForm(item = {}) { return `${field(text('name'), 'name', item.name, 'text', true)}${field(text('phone'), 'phone', item.phone, 'tel', true)}${field(text('email'), 'email', item.email, 'email')}${area(text('notes'), 'notes', item.notes)}`; }
  async function renderCrudList(table, headers, cells, formFactory, extraActions = () => '') { loadingView(); try { const data = await query(table, { order: 'created_at' }); state.cache[table] = data; const rows = data.map((item) => `<tr>${cells(item)}<td><div class="row-actions">${extraActions(item)}<button class="small-button" data-edit="${table}" data-id="${item.id}">${text('edit')}</button><button class="small-button danger" data-delete="${table}" data-id="${item.id}">${text('delete')}</button></div></td></tr>`).join(''); renderShell(text(table), `<div class="toolbar"><input id="module-search" placeholder="${esc(text('search'))}"><button class="button button-primary" id="add-record">+ ${text('add')}</button></div><div id="module-table">${tableView(headers, rows)}</div>`); $('#add-record').addEventListener('click', () => openCrud(table, null, formFactory)); $$('[data-edit="' + table + '"]').forEach((button) => button.addEventListener('click', () => openCrud(table, state.cache[table].find((item) => item.id === button.dataset.id), formFactory))); $$('[data-history]').forEach((button) => button.addEventListener('click', () => showPatientHistory(button.dataset.history))); $('#module-search').addEventListener('input', (event) => { const value = event.target.value.toLowerCase(); $$('#module-table tbody tr').forEach((row) => { row.hidden = !row.textContent.toLowerCase().includes(value); }); }); wireDeleteButtons(); } catch (error) { renderShell(text(table), `<div class="error-state">${esc(normalizeError(error))}</div>`); } }
  function openCrud(table, item, formFactory) { const dialog = modal(item ? text('edit') : text('add'), formFactory(item || {})); dialog.querySelector('#modal-form').addEventListener('submit', async (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); ['is_active'].forEach((key) => { if (key in values) values[key] = values[key] === 'true'; }); ['price', 'sort_order'].forEach((key) => { if (key in values && values[key] === '') values[key] = null; }); try { await save(table, item?.id, values); dialog.remove(); toast(text('saved')); navigate(table); } catch (error) { toast(normalizeError(error), true); } }); }
  function wireDeleteButtons() { $$('[data-delete]').forEach((button) => button.addEventListener('click', async () => { if (!window.confirm(text('confirmDelete'))) return; try { await remove(button.dataset.delete, button.dataset.id); toast(text('deleted')); navigate(state.section); } catch (error) { toast(normalizeError(error), true); } })); }
  async function showPatientHistory(patientId) { try { const patient = state.cache.patients.find((item) => item.id === patientId); const history = await query('appointments', { order: 'preferred_date', filters: { patient_id: patientId } }); const rows = history.map((item) => `<tr><td>${esc(item.preferred_date || '-')}</td><td>${esc(item.service || '-')}</td><td>${statusBadge(item.status)}</td></tr>`).join(''); const dialog = modal(`${text('details')}: ${patient?.name || ''}`, tableView([text('date'), text('service'), text('status')], rows), text('cancel')); dialog.querySelector('#modal-form').remove(); } catch (error) { toast(normalizeError(error), true); } }

  async function renderServices() { await renderCrudList('services', [text('name'), text('price'), text('status'), text('actions')], (item) => `<td>${esc(state.lang === 'ar' ? item.name_ar : item.name_en)}</td><td>${esc(item.price ?? '-')}</td><td>${item.is_active ? statusBadge('active') : statusBadge('inactive')}</td>`, serviceForm); }
  function serviceForm(item = {}) { return `${field('Arabic name', 'name_ar', item.name_ar, 'text', true)}${field('English name', 'name_en', item.name_en, 'text', true)}${area('Arabic description', 'description_ar', item.description_ar)}${area('English description', 'description_en', item.description_en)}${field(text('price'), 'price', item.price, 'number')}${field(text('image'), 'image_path', item.image_path)}${field('Sort order', 'sort_order', item.sort_order || 0, 'number')}<label>${text('active')}<select name="is_active"><option value="true" ${item.is_active !== false ? 'selected' : ''}>${text('active')}</option><option value="false" ${item.is_active === false ? 'selected' : ''}>${text('inactive')}</option></select></label>`; }
  async function renderGallery() { await renderCrudList('gallery', [text('image'), text('title'), text('category'), text('status'), text('actions')], (item) => `<td>${esc(item.image_path)}</td><td>${esc(state.lang === 'ar' ? item.title_ar : item.title_en)}</td><td>${esc(item.category || '-')}</td><td>${item.is_active ? statusBadge('active') : statusBadge('inactive')}</td>`, galleryForm); }
  function galleryForm(item = {}) { return `${field(text('image'), 'image_path', item.image_path, 'text', true)}${field('Arabic title', 'title_ar', item.title_ar)}${field('English title', 'title_en', item.title_en)}${field(text('category'), 'category', item.category)}${field('Sort order', 'sort_order', item.sort_order || 0, 'number')}<label>${text('active')}<select name="is_active"><option value="true" ${item.is_active !== false ? 'selected' : ''}>${text('active')}</option><option value="false" ${item.is_active === false ? 'selected' : ''}>${text('inactive')}</option></select></label>`; }

  async function renderDoctor() { try { const data = await query('doctor_profile', { order: 'created_at', limit: 1 }); const item = data[0] || {}; renderShell(text('doctorProfile'), `<form id="profile-form" class="entity-form">${field('Arabic name', 'name_ar', item.name_ar || 'عبدالرحمن محب', 'text', true)}${field('English name', 'name_en', item.name_en || 'Abdurahman Moheb', 'text', true)}${area('Arabic biography', 'bio_ar', item.bio_ar)}${area('English biography', 'bio_en', item.bio_en)}${area(text('qualifications'), 'credentials_en', item.credentials_en)}${area(text('fellowship'), 'fellowship_en', item.fellowship_en)}${field(text('image'), 'image_path', item.image_path || 'assets/images/doctor/doctor.jpg')}${field(text('instagram'), 'instagram_url', item.instagram_url)}<div class="form-actions"><button class="button button-primary" type="submit">${text('save')}</button></div></form>`); $('#profile-form').addEventListener('submit', async (event) => { event.preventDefault(); try { const values = Object.fromEntries(new FormData(event.currentTarget)); await save('doctor_profile', item.id, values); toast(text('saved')); } catch (error) { toast(normalizeError(error), true); } }); } catch (error) { renderShell(text('doctorProfile'), `<div class="error-state">${esc(normalizeError(error))}</div>`); } }
  async function renderSettings() { try { const data = await query('clinic_settings', { order: 'created_at', limit: 1 }); const item = data[0] || {}; renderShell(text('clinicSettings'), `<form id="settings-form" class="entity-form">${field('Arabic clinic name', 'clinic_name_ar', item.clinic_name_ar || 'عيادة الدكتور عبدالرحمن محب', 'text', true)}${field('English clinic name', 'clinic_name_en', item.clinic_name_en || 'Dr. Abdurahman Moheb Dental Clinic', 'text', true)}${field(text('email'), 'email', item.email, 'email')}${field(text('phone'), 'phone', item.phone, 'tel')}${field('WhatsApp', 'whatsapp', item.whatsapp, 'tel')}${field(text('googleMaps'), 'google_maps_url', item.google_maps_url, 'url')}${area('العنوان العربي', 'address_ar', item.address_ar)}${area('English address', 'address_en', item.address_en)}${area('ساعات العمل بالعربية', 'working_hours_ar', item.working_hours_ar)}${area('Working hours', 'working_hours_en', item.working_hours_en)}${field(text('instagram'), 'instagram_url', item.instagram_url, 'url')}${field('Facebook', 'facebook_url', item.facebook_url, 'url')}<div class="form-actions"><button class="button button-primary" type="submit">${text('save')}</button></div></form>`); $('#settings-form').addEventListener('submit', async (event) => { event.preventDefault(); try { const values = Object.fromEntries(new FormData(event.currentTarget)); await save('clinic_settings', item.id, values); toast(text('saved')); } catch (error) { toast(normalizeError(error), true); } }); } catch (error) { renderShell(text('clinicSettings'), `<div class="error-state">${esc(normalizeError(error))}</div>`); } }
  async function renderMessages() { loadingView(); try { const data = await query('contact_messages', { order: 'created_at' }); state.cache.contact_messages = data; const rows = data.map((item) => `<tr><td>${esc(item.name)}</td><td>${esc(item.phone || '-')}</td><td class="message-cell">${esc(item.message)}</td><td>${statusBadge(item.status)}</td><td><div class="row-actions">${item.status === 'unread' ? `<button class="small-button" data-mark-read="${item.id}">${text('markRead')}</button>` : ''}<button class="small-button danger" data-delete="contact_messages" data-id="${item.id}">${text('delete')}</button></div></td></tr>`).join(''); renderShell(text('messages'), `<div class="toolbar"><input id="module-search" placeholder="${esc(text('search'))}"></div><div id="module-table">${tableView([text('name'), text('phone'), text('message'), text('status'), text('actions')], rows)}</div>`); $('#module-search').addEventListener('input', (event) => { const value = event.target.value.toLowerCase(); $$('#module-table tbody tr').forEach((row) => { row.hidden = !row.textContent.toLowerCase().includes(value); }); }); $$('[data-mark-read]').forEach((button) => button.addEventListener('click', async () => { try { await save('contact_messages', button.dataset.markRead, { status: 'read' }); toast(text('saved')); renderMessages(); } catch (error) { toast(normalizeError(error), true); } })); wireDeleteButtons(); } catch (error) { renderShell(text('messages'), `<div class="error-state">${esc(normalizeError(error))}</div>`); } }

  const renderers = { overview: renderOverview, appointments: renderAppointments, patients: renderPatients, services: renderServices, gallery: renderGallery, doctor: renderDoctor, settings: renderSettings, messages: renderMessages };
  async function navigate(section) { state.section = section; $$('.nav-item').forEach((item) => item.classList.toggle('active', item.dataset.section === section)); $('#sidebar').classList.remove('open'); await renderers[section](); }
  function wireDashboard() { $('#admin-email').textContent = state.user.email; $$('.nav-item').forEach((button) => button.addEventListener('click', () => navigate(button.dataset.section))); $('#menu-button').addEventListener('click', () => $('#sidebar').classList.toggle('open')); $('#logout-button').addEventListener('click', async () => { await state.client.auth.signOut(); toast(text('signedOut')); show('login-view'); }); navigate('overview'); show('dashboard-view'); }
  async function handleLogin(event) { event.preventDefault(); const form = event.currentTarget; const message = $('#login-message'); const submit = form.querySelector('button[type="submit"]'); message.hidden = true; submit.disabled = true; try { const { data, error } = await state.client.auth.signInWithPassword({ email: $('#login-email').value.trim(), password: $('#login-password').value }); if (error) throw error; if (!data.user || data.user.email.toLowerCase() !== ADMIN_EMAIL) { await state.client.auth.signOut(); throw new Error('Unauthorized'); } state.user = data.user; wireDashboard(); } catch (error) { message.textContent = error.message === 'Unauthorized' ? text('accessDenied') : text('loginFailed'); message.className = 'form-message error'; message.hidden = false; } finally { submit.disabled = false; } }
  async function start() { applyLanguage(); $$('[data-language-toggle]').forEach((button) => button.addEventListener('click', () => { state.lang = state.lang === 'ar' ? 'en' : 'ar'; localStorage.setItem('admin_lang', state.lang); applyLanguage(); if (!$('#dashboard-view').hidden) navigate(state.section); })); $('#login-form').addEventListener('submit', handleLogin); show('loading-view'); try { const env = await loadEnvironment(); state.client = window.supabase.createClient(env.VITE_SUPABASE_URL, env.VITE_SUPABASE_PUBLISHABLE_KEY, { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true } }); const { data, error } = await state.client.auth.getSession(); if (error) throw error; if (data.session && data.session.user.email.toLowerCase() === ADMIN_EMAIL) { state.user = data.session.user; wireDashboard(); } else { if (data.session) await state.client.auth.signOut(); show('login-view'); } state.client.auth.onAuthStateChange((_event, session) => { if (!session) show('login-view'); }); } catch (error) { show('configuration-view'); } }
  start();
})();
